window.TITO_DATA = {
  "title": "Tito Goes to NY",
  "tagline": "Downtown, 2 or 3 roommates, max $2,500 each",
  "updated": "2026-09-24T08:57:54-04:00",
  "updatedLabel": "24 Sep 2026, 8:57 AM ET",
  "perPerson": 2500,
  "empty": "Nothing in this filter.",
  "listings": [
    {
      "id": "630-e-9th-st-bw",
      "name": "630 East 9th Street #BW",
      "headline": "Split-bedroom 2BR / 1BA at $3,400 \u2014 both rooms windowed",
      "rent": 3400,
      "address": "630 E 9th St #BW, New York, NY 10009",
      "neighborhood": "East Village",
      "beds": 2,
      "baths": 1,
      "sqft": null,
      "available": "Immediate \u2014 listed 17 Jun 2026",
      "source": "Zumper / Frank Benbelaid",
      "ref": "address page unit BW \u00b7 listed 17 Jun 2026 \u00b7 73 days on market \u00b7 dateModified 29 Aug 2026",
      "url": "https://www.zumper.com/address/630-e-9th-st-new-york-ny-10009-usa",
      "photo": "photos/630-e-9th-st-bw.jpg",
      "why": "$1,700 each. Live Available unit on the building page. Copy names split bedrooms, each windowed, full kitchen with dishwasher / breakfast bar, hardwood, subway-tile bath. Pets OK. Laundry in building. Near Tompkins Square Park.",
      "note": "BW is likely a basement/garden unit \u2014 tour the light. Same 73-day Frank Benbelaid feed as 412 E 9th. Cheap enough to be stale. Fees: first month + security + credit check. Walk-up.",
      "added": "29 Aug 2026"
    },
    {
      "id": "e-14th-st-19",
      "name": "E 14th Street #19",
      "headline": "2BR / 1BA at $3,960 near Union Square",
      "rent": 3960,
      "address": "E 14th St #19, New York, NY 10009",
      "neighborhood": "East Village",
      "beds": 2,
      "baths": 1,
      "sqft": null,
      "available": "Tours 25\u201328 Aug",
      "source": "Zumper",
      "ref": "61868924",
      "url": "https://www.zumper.com/listings/61868924/2-bedroom-east-village-new-york-ny",
      "photo": null,
      "why": "Lowest 2BR on the board. Pets, hardwood, high ceilings, brownstone laundry.",
      "note": "Generic copy. Street number hidden. Tour to confirm two real bedrooms.",
      "added": "23 Aug 2026"
    },
    {
      "id": "e-14th-st-26",
      "name": "E 14th Street #26",
      "headline": "2BR / 1BA at $4,050 near Union Square",
      "rent": 4050,
      "address": "E 14th St #26, New York, NY 10009",
      "neighborhood": "East Village",
      "beds": 2,
      "baths": 1,
      "sqft": null,
      "available": "Tours 26\u201329 Aug",
      "source": "Zumper",
      "ref": "61868923",
      "url": "https://www.zumper.com/listings/61868923/2-bedroom-east-village-new-york-ny",
      "photo": null,
      "why": "$2,025 each if both rooms are real. Pets, hardwood, high ceilings, brownstone laundry.",
      "note": "Generic copy. Same feed as #19. Tour to confirm two bedrooms.",
      "added": "24 Aug 2026"
    },
    {
      "id": "23-jones-st-16",
      "name": "23 Jones Street #16",
      "headline": "Pet-friendly pre-war 2BR, cheapest West Village two-bed tonight",
      "rent": 4200,
      "address": "23 Jones St #16, New York, NY 10014",
      "neighborhood": "West Village",
      "beds": 2,
      "baths": 1,
      "sqft": null,
      "available": "11 Sep 2026",
      "source": "Zumper",
      "ref": "listings/18249642p \u00b7 WV 2BR \u00b7 verified 15 Sep 2026 \u00b7 listing_status 1",
      "url": "https://www.zumper.com/listings/18249642p/2-bedroom-west-village-new-york-ny",
      "photo": null,
      "why": "Only West Village 2BR at or under $5,000. Pets, fireplace, balcony, hardwood.",
      "note": "Tour to confirm both rooms fit queens. $2,100 each.",
      "added": "23 Aug 2026"
    },
    {
      "id": "e-14th-st-21",
      "name": "E 14th Street #21",
      "headline": "Verified 2BR / 1BA, recent price drop",
      "rent": 4300,
      "address": "E 14th St #21, New York, NY 10003",
      "neighborhood": "East Village",
      "beds": 2,
      "baths": 1,
      "sqft": null,
      "available": "Tours 25\u201328 Aug",
      "source": "Zumper",
      "ref": "64622167",
      "url": "https://www.zumper.com/listings/64622167/2-bedroom-east-village-new-york-ny",
      "photo": null,
      "why": "$2,150 each. EV / Union Square edge. Pets.",
      "note": "Confirm both rooms are real bedrooms, not a flex.",
      "added": "23 Aug 2026"
    },
    {
      "id": "avenue-b-6",
      "name": "Avenue B #6",
      "headline": "2BR / 1BA at $4,395 \u2014 generously sized bedrooms",
      "rent": 4395,
      "address": "Avenue B #6, New York, NY 10009",
      "neighborhood": "East Village",
      "beds": 2,
      "baths": 1,
      "sqft": null,
      "available": "Tours 30 Aug\u20132 Sep",
      "source": "Zumper / Manhattan Realty Group",
      "ref": "listings/65108839 \u00b7 posted 14 Aug 2026 \u00b7 updated 8 hours ago",
      "url": "https://www.zumper.com/listings/65108839/2-bedroom-east-village-new-york-ny",
      "photo": "photos/avenue-b-6.jpg",
      "why": "$2,198 each. Dedicated Zumper page live at $4,395. Highlights name generously sized bedrooms plus renovated kitchen, dishwasher, stainless appliances, comfortable living room. In-unit laundry visible in listing photo.",
      "note": "Street number hidden (10009). Amenity tags also list balcony/fireplace/no-fee \u2014 treat those as feed tags until a tour. Not the Realtor 44 Avenue B #12 penthouse.",
      "added": "28 Aug 2026"
    },
    {
      "id": "243-e-2nd-st-2b",
      "name": "243 East 2nd Street #2B",
      "headline": "True queen-bed 2BR / 1BA at $4,500 \u2014 in-unit laundry",
      "rent": 4500,
      "address": "243 E 2nd St #2B, New York, NY 10009",
      "neighborhood": "East Village",
      "beds": 2,
      "baths": 1,
      "sqft": null,
      "available": "Tours 31 Aug\u20133 Sep",
      "source": "Zumper",
      "ref": "address page \u00b7 datePosted 22 Mar 2025 \u00b7 dateModified 29 Aug 2026 \u00b7 updated 11 hours ago",
      "url": "https://www.zumper.com/address/243-e-2nd-st-new-york-ny-10009-usa",
      "photo": "photos/243-e-2nd-st-2b.jpg",
      "why": "Best new 2BR this morning. Live address page at $4,500. Copy names both bedrooms (queen + desk + dresser + closet each), fully separate kitchen and dining, in-unit W/D, gut-renovated walk-up, virtual doorman. $2,250 each.",
      "note": "Stale-date risk: datePosted 22 Mar 2025. Zumper page is live this morning with a price and tour dates. Call before touring. No dedicated /listings/ URL.",
      "added": "29 Aug 2026"
    },
    {
      "id": "630-e-9th-st-20",
      "name": "630 East 9th Street #20",
      "headline": "True 2BR / 1BA at $4,650 \u2014 two windows in each bedroom",
      "rent": 4650,
      "address": "630 E 9th St #20, New York, NY 10009",
      "neighborhood": "East Village",
      "beds": 2,
      "baths": 1,
      "sqft": null,
      "available": "Listed 1 Jul 2026 \u2014 still marked Available",
      "source": "Zumper / Frank Benbelaid",
      "ref": "address page unit 20 \u00b7 listed 17 Jun 2026 \u00b7 73 days on market \u00b7 dateModified 29 Aug 2026",
      "url": "https://www.zumper.com/address/630-e-9th-st-new-york-ny-10009-usa",
      "photo": "photos/630-e-9th-st-20.jpg",
      "why": "$2,325 each. Live Available on the same building page as #BW. Copy names each bedroom with two windows and closet space, exposed brick in the living room and one bedroom, east-facing garden/city views. Pets welcome.",
      "note": "Stale-date risk: copy still says available July 1; 73 days on market. Same walk-up / one bath / Frank Benbelaid pattern as 412 E 9th. Call before touring. Photo is a building-gallery image, not confirmed unit-specific.",
      "added": "29 Aug 2026"
    },
    {
      "id": "e-14th-st-9a",
      "name": "E 14th Street #9A",
      "headline": "Renovated 2BR / 1BA, 4-room layout",
      "rent": 4750,
      "address": "E 14th St #9A, New York, NY 10003",
      "neighborhood": "East Village",
      "beds": 2,
      "baths": 1,
      "sqft": null,
      "available": "Inquire",
      "source": "Zumper",
      "ref": "65167961",
      "url": "https://www.zumper.com/listings/65167961/2-bedroom-east-village-new-york-ny",
      "photo": null,
      "why": "Copy names two bedrooms and a 4-room layout. Hardwood, city views, live-in super. $2,375 each.",
      "note": "No dedicated listing URL this morning. Not StuyTown #9G.",
      "added": "24 Aug 2026"
    },
    {
      "id": "101-thompson-st-5",
      "name": "101 Thompson Street #5",
      "headline": "SoHo sponsor 2BR at the $4,995 cap",
      "rent": 4995,
      "address": "101 Thompson St #5, New York, NY 10012",
      "neighborhood": "SoHo",
      "beds": 2,
      "baths": 1,
      "sqft": null,
      "available": "Inquire",
      "source": "Zumper",
      "ref": "address page AggregateOffer $4995 \u00b7 Updated 5+ Days Ago \u00b7 verified 15 Sep 2026",
      "url": "https://www.zumper.com/address/101-thompson-st-new-york-ny-10012-usa",
      "photo": null,
      "why": "First SoHo 2BR at or under $5k. Two bedrooms, hardwood, no board approval. $2,498 each.",
      "note": "Walk-up. Photos are virtually staged. Listed 17 Aug.",
      "added": "24 Aug 2026"
    },
    {
      "id": "208-e-7th-st-4g",
      "name": "208 East 7th Street #4G",
      "headline": "Renovated true 2BR / 1BA at $4,995 \u2014 in-unit W&D near Tompkins",
      "rent": 4995,
      "address": "208 E 7th St #4G, New York, NY 10009",
      "neighborhood": "East Village",
      "beds": 2,
      "baths": 1,
      "sqft": null,
      "available": "Listed 16 Sep 2026 \u2014 Available",
      "source": "Zumper",
      "ref": "listings/29577205p \u00b7 listing_id 65342968 \u00b7 datePosted 16 Sep 2026 \u00b7 listing_status 1 \u00b7 verified 16 Sep 2026",
      "url": "https://www.zumper.com/listings/29577205p/2-bedroom-east-village-new-york-ny",
      "photo": "photos/208-e-7th-st-4g.jpg",
      "why": "$2,498 each. Dedicated Zumper page live at $4,995 this morning. Copy names a renovated 2-bedroom with spacious bedrooms, in-unit W&D, dishwasher, hardwood, updated kitchen & bath, pet-friendly, near Tompkins Square Park.",
      "note": "Feed is realty_mx but copy is unit-specific (not modern-luxury ROS boilerplate). date_available field shows 2016/01/21 \u2014 treat as stale feed metadata; page is listing_status 1 with today's datePosted. Tour to confirm both rooms fit queens.",
      "added": "16 Sep 2026"
    },
    {
      "id": "430-e-13th-st-5f",
      "name": "430 East 13th Street #5F",
      "headline": "True 2BR / 1BA at $4,995 \u2014 Oct 1 move-in, in-unit W/D, courtyard building",
      "rent": 4995,
      "address": "430 E 13th St #5F, New York, NY 10009",
      "neighborhood": "East Village",
      "beds": 2,
      "baths": 1,
      "sqft": null,
      "available": "October 1st move-in \u2014 listed 19 Sep 2026",
      "source": "Zumper / Real New York APARTMENTS \u00b7 RealtyMX",
      "ref": "listing_id 65375248 \u00b7 pl_id 5203921 \u00b7 /listings/5203921p \u00b7 datePosted 19 Sep 2026 ~11:13 AM ET \u00b7 listing_status 1 \u00b7 verified 20 Sep 2026",
      "url": "https://www.zumper.com/listings/5203921p/2-bedroom-east-village-new-york-ny",
      "photo": "photos/430-e-13th-st-5f.jpg",
      "why": "$2,497 each. Dedicated Zumper page opened this morning at $4,995. Copy names a true East Village 2-bedroom with hardwood, in-unit laundry, dishwasher, and a European-style private courtyard building. Under the 2BR cap. October 1 move-in.",
      "note": "New overnight listing (created/listed 19 Sep ~11:13 AM ET). Feed is realty_mx (realnyproperties) but copy is unit/building-specific (not modern-luxury ROS boilerplate). Tour to confirm both rooms fit queens. Staging photo: /workspace/tito-ny-photos-staging-2026-09-20/430-e-13th-st-5f.jpg.",
      "added": "20 Sep 2026"
    },
    {
      "id": "e-13th-st-2c",
      "name": "E 13th Street #2C",
      "headline": "2BR / 1BA with in-unit W/D at the $5k cap",
      "rent": 4995,
      "address": "E 13th St #2C, New York, NY 10009",
      "neighborhood": "East Village",
      "beds": 2,
      "baths": 1,
      "sqft": null,
      "available": "Tours 25\u201328 Aug",
      "source": "Zumper",
      "ref": "64595265",
      "url": "https://www.zumper.com/listings/64595265/2-bedroom-east-village-new-york-ny",
      "photo": null,
      "why": "In-unit laundry, dishwasher, roof deck, pets, brownstone.",
      "note": "At the 2BR cap. Tour this exact unit; similar E 13th ads look syndicated.",
      "added": "23 Aug 2026"
    },
    {
      "id": "412-e-9th-st-8",
      "name": "412 East 9th Street #8",
      "headline": "True 3BR / 1BA at $5,800 \u2014 queen rooms with windows (back Available)",
      "rent": 5800,
      "address": "412 E 9th St #8, New York, NY 10009",
      "neighborhood": "East Village",
      "beds": 3,
      "baths": 1,
      "sqft": null,
      "available": "Listed 17 Jun 2026 \u2014 Available as of 1 Jul 2026; building page still Available",
      "source": "Zumper / Frank Benbelaid (Brown Harris Stevens)",
      "ref": "listing_id 64628549 \u00b7 address page unit 8 \u00b7 listed 17 Jun 2026 \u00b7 76 DOM \u00b7 listing_status 1 \u00b7 modified 1 Sep 2026 ~8:23 PM ET",
      "url": "https://www.zumper.com/address/412-e-9th-st-new-york-ny-10009-usa",
      "photo": "photos/412-e-9th-st-8.jpg",
      "why": "$1,933 each. Copy names a true 3BR: all bedrooms fit queen-size beds, have closets, and all have windows. Pets welcome. Exposed brick, new kitchen, subway-tiled bath. South/East light overlooking gardens.",
      "note": "Re-add: dropped 31 Aug when gone from Available; live again today (3 units Available at building; EV 3BR lowest-price still shows #8 $5,800). Stale-date risk: avail dated 1 Jul 2026, 76 DOM. Call before touring. Walk-up, one bath.",
      "added": "2 Sep 2026"
    },
    {
      "id": "211-avenue-a-15",
      "name": "211 Avenue A #15",
      "headline": "Queen-bedroom 3BR / 1BA at $6,250 \u2014 roof deck",
      "rent": 6250,
      "address": "211 Avenue A #15, New York, NY 10009",
      "neighborhood": "East Village",
      "beds": 3,
      "baths": 1,
      "sqft": null,
      "available": "Copy says Aug 1\u201315 lease start \u2014 still marked live",
      "source": "Zumper",
      "ref": "address page \u00b7 datePosted 27 May 2025 \u00b7 dateModified 29 Aug 2026 \u00b7 updated 11 hours ago",
      "url": "https://www.zumper.com/address/211-ave-a-new-york-ny-10009-usa",
      "photo": "photos/211-avenue-a-15.jpg",
      "why": "$2,083 each. Live address page at $6,250. Copy names Queen Size Bedrooms plus dishwasher, hardwood, marble counters, stainless, roof deck, pre-war reno. Under the 3BR cap with better per-person math than most EV 3BRs.",
      "note": "Stale-date risk: datePosted 27 May 2025 and the lease-start window (Aug 1\u201315) is already past. Page still shows a price and tour dates this morning. One bath. Call before touring.",
      "added": "29 Aug 2026"
    },
    {
      "id": "lafayette-st-1f",
      "name": "Lafayette Street #1F",
      "headline": "True 3BR / 2BA at $6,750 \u2014 best 3-roommate split",
      "rent": 6750,
      "address": "Lafayette St #1F, New York, NY 10003",
      "neighborhood": "NoHo",
      "beds": 3,
      "baths": 2,
      "sqft": null,
      "available": "1 Sep 2026",
      "source": "Zumper",
      "ref": "58941135",
      "url": "https://www.zumper.com/listings/58941135/3-bedroom-greenwich-village-new-york-ny",
      "photo": null,
      "why": "$2,250 each. All three bedrooms queen-sized with windows and closets. Two baths. Pets and shares OK.",
      "note": "Broker fee. First floor. Zumper tags it Greenwich Village; listing copy says NoHo.",
      "added": "23 Aug 2026"
    },
    {
      "id": "350-e-13th-st-4",
      "name": "350 East 13th Street #4",
      "headline": "True 3BR / 2BA gut reno at $6,950 \u2014 big living room + in-unit W/D",
      "rent": 6950,
      "address": "350 E 13th St #4, New York, NY 10003",
      "neighborhood": "East Village",
      "beds": 3,
      "baths": 2,
      "sqft": null,
      "available": "Inquire \u2014 Zumper listing_status Available; date_available blank",
      "source": "Zumper / Natalia Anhel (Living Real Estate Group, LLC) \u00b7 RealtyMX",
      "ref": "listing_id 54760287 \u00b7 /listings/4325892p \u00b7 listed 5 Apr 2025 \u00b7 modified 2 Sep 2026 ~2:26 AM ET \u00b7 listing_status 1 \u00b7 min_lease_days 360",
      "url": "https://www.zumper.com/listings/4325892p/3-bedroom-east-village-new-york-ny",
      "photo": "photos/350-e-13th-st-4.jpg",
      "why": "$2,317 each. Dedicated listings page opened this morning with named true 3BR copy: 3 Queen Size Bedrooms, 2 Full Baths, Big Living Room, in-unit W/D, stainless appliances, high ceilings, marble baths. Two baths is rare at this budget. Photo shows open living/kitchen + stacked W/D + multiple bedroom doors.",
      "note": "Reappeared: prior mornings (29 Aug\u20134 Sep) address/building page was Notify me / rent \"-\". Today dedicated /listings/ page is live at $6,950; building address page still has empty units and provider URL resolves to Living NY homepage (not the unit). Stale-date / syndication risk \u2014 call before touring.",
      "added": "6 Sep 2026"
    },
    {
      "id": "412-e-9th-st-9",
      "name": "412 East 9th Street #9",
      "headline": "3BR / 1BA at $6,995 \u2014 same building as #8",
      "rent": 6995,
      "address": "412 E 9th St #9, New York, NY 10009",
      "neighborhood": "East Village",
      "beds": 3,
      "baths": 1,
      "sqft": null,
      "available": "Listed 1 Aug 2026 \u2014 still marked Available",
      "source": "Zumper / Frank Benbelaid",
      "ref": "address page unit 9 \u00b7 listed 4 Jul 2026 \u00b7 55 days on market \u00b7 building updated 6 hours ago",
      "url": "https://www.zumper.com/address/412-e-9th-st-new-york-ny-10009-usa",
      "photo": "photos/412-e-9th-st-9.jpg",
      "why": "$2,332 each. Still Available on the live building page. High ceilings, exposed brick, six windows, separate kitchen with dishwasher. Pets allowed.",
      "note": "Weaker bedroom copy than #8. Stale-date risk: avail dated 1 Aug 2026, 55 DOM. Call before touring. Walk-up, one bath.",
      "added": "28 Aug 2026"
    },
    {
      "id": "37-3rd-ave-1212",
      "name": "37 3rd Avenue #1212",
      "headline": "True 3BR / 2BA \u00b7 1,200 sqft at $7,000 (was $7,700)",
      "rent": 7000,
      "address": "37 3rd Ave #1212, New York, NY 10003",
      "neighborhood": "East Village",
      "beds": 3,
      "baths": 2,
      "sqft": 1200,
      "available": "Immediate - price cut to $7,000 (was $7,700)",
      "source": "Zumper / The Bouklis Group \u00b7 Leonardo Mora",
      "ref": "listings/29462106p \u00b7 listing_id 65389579 \u00b7 listing_status 1 \u00b7 1200 sqft \u00b7 verified 23 Sep 2026",
      "url": "https://www.zumper.com/listings/29462106p/3-bedroom-east-village-new-york-ny",
      "photo": "photos/37-3rd-ave-1212.jpg",
      "why": "$2,333 each. Large 3-bedroom with oversized windows, plank hardwood, granite + GE stainless, subway-tile baths, walk-in closets. Building amenity stack: 24/7 concierge/doorman, fitness, roof deck, laundry on each floor, bike storage. Was over the $7,500 cap at $7,700; now at the per-person ceiling.",
      "note": "Doorman luxury building on 3rd Ave (EV / NoHo edge). Realty_mx syndication but unit-specific copy and 1,200 sqft. Confirm true three bedrooms on tour (not flex).",
      "added": "23 Sep 2026"
    },
    {
      "id": "49-e-7th-st",
      "name": "49 East 7th Street",
      "headline": "3BR / 2BA duplex at $7,000 - garden + in-unit laundry",
      "rent": 7000,
      "address": "49 E 7th St, New York, NY 10003",
      "neighborhood": "East Village",
      "beds": 3,
      "baths": 2,
      "sqft": null,
      "available": "ASAP - re-listed live 23 Sep 2026",
      "source": "Zumper / listanza \u00b7 Bianca Fields MX",
      "ref": "listings/20416815p \u00b7 ZMP42801079 \u00b7 listing_status 1 \u00b7 verified 23 Sep 2026 \u00b7 was dropped 21 Sep as off-market",
      "url": "https://www.zumper.com/listings/20416815p/3-bedroom-east-village-new-york-ny",
      "photo": "photos/49-e-7th-st.jpg",
      "why": "$2,333 each. Back live after the 21 Sep off-market drop. Renovated 3-bedroom duplex with generous bedroom sizes (3rd bedroom on the lower level), two baths, massive private garden, in-unit W/D, Bosch kitchen, brownstone. Two baths at the cap is rare.",
      "note": "Third bedroom is downstairs - tour it. No unit number on the page. Same ZMP42801079 feed that was on the board before. Call before touring.",
      "added": "23 Sep 2026"
    },
    {
      "id": "322-w-11th-st-17",
      "name": "322 West 11th Street #17",
      "headline": "West Village true 3BR at $7,200 (rare under-cap)",
      "rent": 7200,
      "address": "322 W 11th St #17, New York, NY 10014",
      "neighborhood": "West Village",
      "beds": 3,
      "baths": 1,
      "sqft": null,
      "available": "Immediate - listed live 24 Sep 2026 (Updated 23 Hours Ago)",
      "source": "Zumper / REAL New York",
      "ref": "listings/29638368p \u00b7 listing_id 65398000 \u00b7 listing_status 1 \u00b7 verified 24 Sep 2026",
      "url": "https://www.zumper.com/listings/29638368p/3-bedroom-west-village-new-york-ny",
      "photo": "photos/322-w-11th-st-17.jpg",
      "why": "$2,400 each. Sunny 3-bedroom in the heart of West Village (REAL New York). Hardwood + AC. Stock-photo disclaimer on listing (ask for video tour).",
      "note": "Tour / video to confirm all three rooms and that photos match unit #17. 1 bath for 3 roommates. $2,400 each.",
      "added": "24 Sep 2026"
    },
    {
      "id": "170-e-2nd-st-1e",
      "name": "170 East 2nd Street #1E",
      "headline": "Renovated true 3BR / 1BA at $7,495 \u2014 private patio + in-unit W/D",
      "rent": 7495,
      "address": "170 E 2nd St #1E, New York, NY 10009",
      "neighborhood": "East Village",
      "beds": 3,
      "baths": 1,
      "sqft": null,
      "available": "Listed 18 Sep 2026 \u2014 Available",
      "source": "Zumper / Real New York APARTMENTS \u00b7 RealtyMX",
      "ref": "listing_id 65361243 \u00b7 pl_id 4400053 \u00b7 /listings/4400053p \u00b7 datePosted 18 Sep 2026 ~8:23 AM ET \u00b7 dateModified 18 Sep 2026 ~8:27 AM ET \u00b7 listing_status 1 \u00b7 verified 19 Sep 2026",
      "url": "https://www.zumper.com/listings/4400053p/3-bedroom-east-village-new-york-ny",
      "photo": "photos/170-e-2nd-st-1e.jpg",
      "why": "$2,498 each. Dedicated Zumper page opened this morning at $7,495. Copy names a renovated East Village 3-bedroom with private patio, in-unit W/D, dishwasher, queen/full-size bedrooms with closets in every bedroom, hardwood, stainless, marble counters. Under the 3BR cap.",
      "note": "New overnight listing (datePosted 18 Sep). Feed is realty_mx but copy is unit-specific (not modern-luxury ROS boilerplate). date_available field blank/stale elsewhere in feed \u2014 treat as syndication metadata; page is listing_status 1 with yesterday's datePosted. One bath. Tour to confirm all three rooms fit. Staging photo: /workspace/tito-ny-photos-staging-2026-09-19/170-e-2nd-st-1e.jpg.",
      "added": "19 Sep 2026"
    },
    {
      "id": "44-avenue-b-6-3r",
      "name": "44 Avenue B #6-3R",
      "headline": "Renovated true 3BR / 1.5BA at the $7,500 cap \u2014 balcony + in-unit W/D + exposed brick",
      "rent": 7500,
      "address": "44 Avenue B #6-3R, New York, NY 10009",
      "neighborhood": "East Village",
      "beds": 3,
      "baths": 1.5,
      "sqft": 1000,
      "available": "15 Sep 2026 \u2014 Zumper date_available 2026/09/15; listing_status Available",
      "source": "Zumper / Samantha Z \u00b7 Avail",
      "ref": "listing_id 65281654 \u00b7 pl_id 29214585 \u00b7 /listings/29214585p \u00b7 provider avail.61696590 \u00b7 listed 8 Sep 2026 ~1:38 PM ET \u00b7 modified 9 Sep 2026 ~1:44 AM ET \u00b7 listing_status 1",
      "url": "https://www.zumper.com/listings/29214585p/3-bedroom-east-village-new-york-ny",
      "photo": "photos/44-avenue-b-6-3r.jpg",
      "why": "$2,500 each on the nose. Dedicated /listings/ page opened this morning: named renovated 3-bedroom / 1.5-bath with stainless kitchen + dishwasher, in-unit W/D, hardwood, high ceilings, exposed brick, Deco fireplace, private balcony. 1000 sqft. Not flex/furnished/co-living. Same building as dropped #12 (still $8,500 \u2014 do not re-add).",
      "note": "New overnight listing (created 8 Sep). Structured baths=1 + half_bathrooms=1 (copy says 1.5). A second Avail card for the same unit #6-3R also appears at $8,000 (Bernard Richards) \u2014 treat $7,500 Samantha Z page as the live ask and confirm price before touring. Staging photo: /workspace/tito-ny-photos-staging-2026-09-09/44-avenue-b-6-3r.jpg (kitchen + exposed brick).",
      "added": "9 Sep 2026"
    }
  ]
};
